name: nitotv repository
bio: a nitotv repository created by jmd0x

description: a nitotv repository created by jmd0x
external-image: true
picture: assets/images/nitotv.jpg

url: https://jmd0x.github.io/nitotv/

permalink: /:title/


authors:
    repo:
        name: nitotv repository
        bio: a nitotv repository created by jmd0x
        external-image: true
        picture: assets/images/nitotv.jpg
    repo:
        name: nitotv repository
        bio: a nitotv repository created by jmd0x
        external-image: true
        picture: assets/images/nitotv.jpg

width: normal



email: jmd0x@github.io
github: jmd0x

home: false

read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true



plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
